import '@/styles/globals.css'
import Sidebar from '../components/Sidebar'

export const metadata = {
  title: 'ChartGPT',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className='flex'>
          {/* Sidebar */}
          <div className='bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[16rem]'>
            <Sidebar/>
          </div>
          {/* clientProvider - Notification */}
          <div className='bg-[#343541] flex-1'>{children}</div>
        </div>
      </body>
    </html>
  )
}
